
# Docker Compose file for a PHP application with MySQL database

services:
  app:
    container_name: task_list_app
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: task_list_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_list
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always   
volumes:
    db_data:



