services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task-list
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"